const ContentData =[
    { id:'11',
    title: 'Parent Two',
    name:'Anju',
    content:'WEb Developer',
    setValue:' Working as Developer',
  },
  { id:'12',
  title: 'Parent One',
  name:'Krishan Kumar',
  content:' Sales Head',
  setValue:'Working as Head',
},
{ id:'13',
title: 'Child 2',
name:'Aghanya Sharma',
content:'Mont 2',
setValue:'Studing in UKG',
},
{ id:'14',
title: 'Child One',
name:'Rudra Sharma',
content:'Mont 1',
setValue:'Studing in Nursery',
},
  ];
  export default ContentData;